# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc801a857a8c3822b6397021e39b75769f0a7f8b175104307512bb78416f71d24e34b193ab7f664c88c7b104a2e9ec85e9322df6385997fdd359e05545e39b5c

test:
  secret_key_base: d918f9a63b28343a563b8accb20ad00e4bd579d576cf14cc9d0ff18b1f608d12c3fe8efd61f8caffe543e7ad4e3ef7f55ceb1b195d0a9d213f8df9c64e8b9ffc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
